config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'tour_agency/index'
  get 'signup' => 'users#new'


  resources :tours
  resources :shedules
  resources :tour_orders
  resources :users
  # root 'tour_agency#index'
  root 'tours#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shedule.rb
class Shedule < ApplicationRecord
  belongs_to :tour, class_name: '::Tour', foreign_key: :tour_id
end

app/controllers/shedules_controller.rb
class ShedulesController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :admin_user, only: [:edit, :create, :update, :destroy]



  def index
    @shedules = Shedule.all
  end

  def show
    @shedule = Shedule.find(params[:id])
  end

  def new
    @shedule = Shedule.new
  end

  def edit
    @shedule = Shedule.find(params[:id])
  end

  def create
    @shedule = Shedule.new(shedule_params)
    if @shedule.save
      redirect_to @shedule
    else
      render 'new'
    end
  end

  def update
    @shedule = Shedule.find(params[:id])

    if @shedule.update(shedule_params)
      redirect_to @shedule
    else
      render 'edit'
    end
  end

  def destroy
    @shedule = Shedule.find(params[:id])
    @shedule.destroy

    redirect_to shedule_path
  end

  private

  def shedule_params
    params.require(:shedule).permit(:datetimetour, :countplace, :tourcost, :tour_id)
  end


  # Предфильтры

  # Подтверждает вход пользователя
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Пожалуйста войдите в систему."
      redirect_to login_url
    end
  end

  # Подтверждает администратора.
  def admin_user
    flash[:danger] = "У Вас нет прав на действия с расписанием" unless current_user.admin?
    redirect_to(shedules_url) unless current_user.admin?
  end

end

app/helpers/shedules_helper.rb
module ShedulesHelper
end

app/views/shedules/_form.html.erb
<%= form_with model: @shedule, local: true do |form| %>

  <% if @shedule.errors.any? %>
    <div id="error_explanation">
      <h4 style="color: #B00100">
        <%= pluralize(@shedule.errors.count, "error") %> prohibited this sheduleitem from being saved:
      </h4>
      <ul>
        <% @shedule.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-group">
  </div>

  <div class="form-group">
    <%= form.label :datetimetour %><br>
    <%= form.datetime_field :datetimetour, class: "form-control date_time_picker", input_html:
        {data:
             {
                 date_format: "YYYY-MM-DD HH:mm"
             }
        } %>
  </div>


  <%#= form.datetime_field :when, as: :date_time_picker %>

  <div class="form-group">
    <%= form.label :countplace %><br>
    <%= form.number_field :countplace, class: "form-control" %><br>
  </div>
  <div class="form-group">
    <%= form.label :tourcost %><br>
    <%= form.text_field :tourcost, class: "form-control" %><br>
  </div>

  <div class="form-group">
    <%= form.label :tour_id %><br>
    <%#= form.collection_select :tour, Tour.all,:id,:title, {}, {class: 'form-control'} %>
    <%= form.collection_select :tour_id, Tour.all, :id, :title, {prompt: "Выберите экскурсию"}, {class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= form.submit :class => "btn btn-primary" %>
  </div>

<% end %>

app/views/shedules/edit.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href="../" class="navbar-brand">TourAgency</a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Экскурсии', controller: 'tours' %>
        </li>
        <li>
          <%= link_to 'Добавить экскурсию', new_tour_path %>
        </li>
        <li>
          <%= link_to 'Добавить запись в расписание', new_shedule_path %>
        </li>
        <li>
          <%= link_to 'Запись на экскурсию', new_tour_path %>
        </li>
        <li>
          <%= link_to 'Расписание экскурсий', shedules_path %>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-lg-12">
        <h1>Редактировать экскурсию</h1>
        <%= render 'form' %>
        <%= link_to 'К списку экскурсий', tours_path %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6">
    </div>
  </div>
</div>

app/views/shedules/index.html.erb
<%= render 'layouts/mainmenu' %>
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-lg-12">
        <div class="row" style="margin-top: 50px">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        </div>
        <h1>Расписание экскурсий</h1>
        <table class="table table-hover table-bordered">
          <tr>
            <th>Название</th>
            <th>Дата</th>
            <th>Количество мест</th>
            <th>Стоимость, р</th>
            <% if logged_in? %>
              <th></th>
              <th></th>
              <th></th>
            <% end %>

          </tr>
          <% @shedules.each do |shedule| %>
            <tr>
              <td><%= shedule.tour.title %></td>
              <td><%= shedule.datetimetour %></td>
              <td><%= shedule.countplace %></td>
              <td><%= shedule.tourcost %></td>
              <% if logged_in? %>
                <td><%= link_to 'Показать', shedule_path(shedule) %></td>
                <td><%= link_to 'Редактировать', edit_shedule_path(shedule) %></td>
                <td><%= link_to 'Удалить', shedule_path(shedule),
                                method: :delete,
                                data: {confirm: 'Вы уверены?'} %></td>
                </tr>
              <% end %>

          <% end %>
        </table>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6">
    </div>
  </div>
</div>

app/views/shedules/new.html.erb
<%= render 'layouts/mainmenu' %>
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-lg-12">
        <h1>Добавить запись в расписание</h1>
        <%= render 'form' %>
        <%= link_to 'К расписанию', shedules_path %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6">
    </div>
  </div>
</div>

app/views/shedules/show.html.erb
<%= render 'layouts/mainmenu' %>
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-lg-12">
        <h1>Название экскурсии:
          <%= @shedule.tour.title  %>
        </h1>
        <p>Стоимость экскурсии, р:
          <%= @shedule.tourcost %>
        </p>
        <p>
          <strong>Количество мест:</strong>
          <%= @shedule.countplace%>
        </p>
        <%= link_to 'Редактировать', edit_shedule_path(@shedule) %> |
        <%= link_to 'К расписанию', shedules_path %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6">
    </div>
  </div>
</div>