config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'tour_agency/index'
  get 'signup' => 'users#new'


  resources :tours
  resources :shedules
  resources :tour_orders
  resources :users
  # root 'tour_agency#index'
  root 'tours#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tour_order.rb
class TourOrder < ApplicationRecord
  belongs_to :tour, class_name: '::Tour', foreign_key: :tour_id
end

app/controllers/tour_orders_controller.rb
class TourOrdersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :admin_user, only: [:edit, :update, :destroy]



  def index
    @tour_orders = TourOrder.all
  end

  def show
    @tour_order = TourOrder.find(params[:id])
  end

  def new
    t@tour_order = TourOrder.new
  end

  def edit
    @tour_order = TourOrder.find(params[:id])
  end

  def create
    @tour_order = TourOrder.new(tour_order_params)
    if @tour_order.save
      UserMailer.with(user: @user).user_tour.deliver_later
      flash[:danger] = "Сообщение о записи на экскурсию отправлено на ваш эл. адрес"
      redirect_to @tour_order
    else
      render 'new'
    end
  end

  # # Отправляет электронное письмо о записи на экскурсию
  # def send_tourorder_email
  #   UserMailer.user_tour(@tour_order).deliver_now
  # end

  def update
    @tour_order = TourOrder.find(params[:id])

    if @tour_order.update(tour_order_params)
      redirect_to @tour_order
    else
      render 'edit'
    end
  end

  def destroy
    @tour_order = TourOrder.find(params[:id])
    @tour_order.destroy

    # redirect_to tour_order_path
    redirect_to @tour_order
  end

  private

  def tour_order_params
    params.require(:tour_order).permit(:customer, :cellphone, :email, :custdatetour, :tour_id)
  end


  # Предфильтры

  # Подтверждает вход пользователя
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Пожалуйста войдите в систему."
      redirect_to login_url
    end
  end

  # Подтверждает администратора.
  def admin_user
    flash[:danger] = "У Вас нет прав на действия со списком записей на экскурсию" unless current_user.admin?
    redirect_to(tour_orders_url) unless current_user.admin?
  end

end

app/helpers/tour_orders_helper.rb
module TourOrdersHelper
end

app/views/tour_orders/_form.html.erb
<%= form_with model: @tour_order, local: true do |form| %>

  <% if @tour_order.errors.any? %>
    <div id="error_explanation">
      <h4 style="color: #B00100">
        <%= pluralize(@tour_order.errors.count, "error") %> prohibited this sheduleitem from being saved:
      </h4>
      <ul>
        <% @tour_order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  </div>

  <div class="form-group">
    <%= form.label t(:customer) %><br>
    <%= form.text_field :customer, class: "form-control" %><br>
  </div>

  <div class="form-group">
    <%= form.label t(:cellphone) %><br>
    <%= form.phone_field :cellphone, class: "form-control" %><br>
  </div>

  <div class="form-group">
    <%= form.label t(:email) %><br>
    <%= form.email_field :email, class: "form-control" %><br>
  </div>

  <div class="form-group">
    <%= form.label t(:custdatetour) %><br>
    <!--    <%#= form.datetime_field :custdatetour, class: "form-control" %><br>-->
    <%= form.datetime_field :custdatetour, class: "form-control date_time_picker", input_html:
        {data:
             {
                 date_format: "YYYY-MM-DD HH:mm:ss"
             }
        }
    %>
  </div>

  <div class="form-group">
    <%= form.label t(:tour_id) %><br>
    <%#= form.collection_select :tour, Tour.all,:id,:title, {}, {class: 'form-control'} %>
    <%= form.collection_select :tour_id, Tour.all, :id, :title, {prompt: "Выберите экскурсию"}, {class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= form.submit :class => "btn btn-primary" %>
  </div>

<% end %>

app/views/tour_orders/edit.html.erb
<%= render 'layouts/mainmenu' %>
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-lg-12">
        <h1>Редактировать экскурсию</h1>
        <%= render 'form' %>
        <%= link_to 'К списку экскурсий', tours_path %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6">
    </div>
  </div>
</div>

app/views/tour_orders/index.html.erb
<%= render 'layouts/mainmenu' %>
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-lg-12">
        <div class="row" style="margin-top: 50px">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        </div>
        <h1>Записи на экскурсию</h1>
        <table class="table table-hover table-bordered">
          <tr>
            <th>Клиент</th>
            <th>Название</th>
            <th>Номер телефона</th>
            <th>Электронный адрес</th>
            <th>Дата</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
          <% @tour_orders.each do |tour_order| %>
            <tr>
              <td><%= tour_order.customer %></td>
              <td><%= tour_order.tour.title %></td>
              <td><%= tour_order.cellphone %></td>
              <td><%= tour_order.email %></td>
              <td><%= tour_order.custdatetour %></td>
              <td><%= link_to 'Показать', tour_order_path(tour_order) %></td>
              <td><%= link_to 'Редактировать', edit_tour_order_path(tour_order) %></td>
              <td><%= link_to 'Удалить', tour_order_path(tour_order),
                              method: :delete,
                              data: {confirm: 'Вы уверены?'} %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6">
    </div>
  </div>
</div>

app/views/tour_orders/new.html.erb
<%= render 'layouts/mainmenu' %>
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-lg-12">
        <h1>Записаться на экскурсию</h1>
        <%= render 'form' %>
        <% if logged_in? %>
          <%= link_to 'К списку записей на экскурсию', tour_orders_path %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6">
    </div>
  </div>
</div>

app/views/tour_orders/show.html.erb
<%= render 'layouts/mainmenu' %>
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-lg-12">
        <div class="row" style="margin-top: 50px">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        </div>
        <h3>Клиент:
          <%= @tour_order.customer %>
        </h3>
        <h4>Название экскурсии:
          <%= @tour_order.tour.title %>
        </h4>
        <p>Номер телефона:
          <%= @tour_order.cellphone %>
        </p>
        <p>Электронная почта':
          <%= @tour_order.email %>
        </p>
        <p>
          <strong>Дата:</strong>
          <%= @tour_order.custdatetour %>
        </p>
        <% if logged_in? %>
          <%= link_to 'Редактировать', edit_tour_order_path(@tour_order) %> |
          <%= link_to 'К списку записей', tour_orders_path %>
        <% end %>

      </div>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6">
    </div>
  </div>
</div>