config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'tour_agency/index'
  get 'signup' => 'users#new'


  resources :tours
  resources :shedules
  resources :tour_orders
  resources :users
  # root 'tour_agency#index'
  root 'tours#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_many :shedules
  has_many :tour_orders
  validates :title, presence: true,
            length: {minimum: 5}

  def Tour
  end

end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :admin_user, only: [:edit, :create, :update, :destroy, :show, :new, :index]



  def index
    # @tours = Tour.all
    @tours = Tour.paginate(page: params[:page], per_page: 3)

  end

  def show
    @tour = Tour.find(params[:id])
  end

  def new
    @tour = Tour.new
  end

  def edit
    @tour = Tour.find(params[:id])
  end

  def create
    @tour = Tour.new(tour_params)

    if @tour.save
      redirect_to @tour
    else
      render 'new'
    end
  end

  def update
    @tour = Tour.find(params[:id])

    if @tour.update(tour_params)
      redirect_to @tour
    else
      render 'edit'
    end
  end

  def destroy
    @tour = Tour.find(params[:id])
    @tour.destroy

    redirect_to tours_path
  end

  private

  def tour_params
    params.require(:tour).permit(:title, :description)
  end


  # Предфильтры

  # Подтверждает вход пользователя
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Пожалуйста войдите в систему."
      redirect_to login_url
    end
  end

  # Подтверждает администратора.
  def admin_user
    redirect_to(tours_url) unless current_user.admin?
    flash[:danger] = "У Вас нет прав на действия со списком экскурсий" unless current_user.admin?
  end

end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= form_with model: @tour, local: true do |form| %>

  <% if @tour.errors.any? %>
    <div id="error_explanation">
      <h4 style="color: #B00100">
        <%= pluralize(@tour.errors.count, "error") %> prohibited this article from being saved:
      </h4>
      <ul>
        <% @tour.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description,  class: "form-control", id: "tourdescription" %>
  </div>

  <div class="form-group">
    <%= form.submit :class => "btn btn-primary" %>
  </div>

<% end %>

app/views/tours/edit.html.erb
<%= render 'layouts/mainmenu' %>
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-lg-12">
        <h1>Редактировать экскурсию</h1>
        <%= render 'form' %>
        <%= link_to 'К списку экскурсий', tours_path %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6">
    </div>
  </div>
</div>

app/views/tours/index.html.erb
<%= render 'layouts/mainmenu' %>
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-lg-12">
        <div class="row" style="margin-top: 50px">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        </div>
        <h1>Список экскурсий</h1>
        <%= will_paginate %>

        <table class="table table-hover table-bordered">
          <tr>
            <th>Название</th>
            <!--            <th>Описание</th>-->
            <th></th>
            <% if logged_in? %>
              <th></th>
              <th></th>
            <% end %>

          </tr>
          <% @tours.each do |tour| %>
            <tr>
              <td><%= link_to tour.title, tour_path(tour) %></td>
              <!--              <td><%#= tour.description.html_safe %></td>-->
              <td><%= link_to 'Показать', tour_path(tour) %></td>
              <% if logged_in? %>
                <td><%= link_to 'Редактировать', edit_tour_path(tour) %></td>
                <td><%= link_to 'Удалить', tour_path(tour),
                                method: :delete,
                                data: {confirm: 'Вы уверены?'} %></td>
                </tr>
              <% end %>
          <% end %>

        </table>
        <%= will_paginate %>

      </div>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6">
    </div>
  </div>
</div>

app/views/tours/new.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href="../" class="navbar-brand">TourAgency</a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Экскурсии', controller: 'tours' %>
        </li>
        <li>
          <%= link_to 'Добавить экскурсию', new_tour_path %>
        </li>
        <li>
          <%= link_to 'Добавить запись в расписание', new_shedule_path %>
        </li>
        <li>
          <%= link_to 'Запись на экскурсию', new_tour_path %>
        </li>
        <li>
          <%= link_to 'Расписание экскурсий', shedules_path %>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-lg-12">
        <h1>Добавить экскурсию</h1>
        <%#= form_with scope: :tour, local: true do |form| %>
        <%= render 'form' %>
        <%= link_to 'К списку экскурсий', tours_path %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6">
    </div>
  </div>
</div>

app/views/tours/show.html.erb
<%= render 'layouts/mainmenu' %>
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-lg-12">
        <div class="row" style="margin-top: 50px">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        </div>
        <h1>Название экскурсии:
          <%= @tour.title %>
        </h1>
        <p>
          <strong>Описание экскурсии:</strong>
          <%= @tour.description.html_safe %>
        </p>
        <% if logged_in? %>
          <%= link_to 'Редактировать', edit_tour_path(@tour) %> |
          <%= link_to 'К списку экскурсий', tours_path %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6">
    </div>
  </div>
</div>