config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'tour_agency/index'
  get 'signup' => 'users#new'


  resources :tours
  resources :shedules
  resources :tour_orders
  resources :users
  # root 'tour_agency#index'
  root 'tours#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_mainmenu.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href="../" class="navbar-brand">TourAgency</a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Экскурсии', controller: 'tours' %>
        </li>
        <li>
          <%= link_to 'Запись на экскурсию', new_tour_order_path %>
        </li>
        <li>
          <%= link_to 'Расписание экскурсий', shedules_path %>
        </li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Управление экскурсиями
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Добавить экскурсию', new_tour_path %>
              </li>
              <li>
                <%= link_to 'Добавить запись в расписание', new_shedule_path %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
      <!--      <ul class="nav navbar-nav navbar-right">-->
      <!--        <li><%#= link_to "Регистрация", signup_path %></li>-->
      <!--      </ul>-->
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Пользователь
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Профиль", current_user %></li>
              <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
              <% if current_user.admin? %>
                <li><%= link_to "Пользователи", users_path %></li>
              <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "Выйти", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Войти", login_path %></li>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TourAgency</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Custom styles for this template -->
  <link href="https://bootswatch.com/3/assets/css/custom.min.css">
  <script type="text/javascript">
      tinymce.init({
          selector: 'textarea#tourdescription',
          plugins: 'image code',
          toolbar: 'undo redo | link image | code',
          height: 500,
          /* enable title field in the Image dialog*/
          image_title: true,
          /* enable automatic uploads of images represented by blob or data URIs*/
          automatic_uploads: true,
          /*
            URL of our upload handler (for more details check: https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_url)
            images_upload_url: 'postAcceptor.php',
            here we add custom filepicker only to Image dialog
          */
          file_picker_types: 'image',
          /* and here's our custom image picker*/
          file_picker_callback: function (cb, value, meta) {
              var input = document.createElement('input');
              input.setAttribute('type', 'file');
              input.setAttribute('accept', 'image/*');

              /*
                Note: In modern browsers input[type="file"] is functional without
                even adding it to the DOM, but that might not be the case in some older
                or quirky browsers like IE, so you might want to add it to the DOM
                just in case, and visually hide it. And do not forget do remove it
                once you do not need it anymore.
              */

              input.onchange = function () {
                  var file = this.files[0];

                  var reader = new FileReader();
                  reader.onload = function () {
                      /*
                        Note: Now we need to register the blob in TinyMCEs image blob
                        registry. In the next release this part hopefully won't be
                        necessary, as we are looking to handle it internally.
                      */
                      var id = 'blobid' + (new Date()).getTime();
                      var blobCache =  tinymce.activeEditor.editorUpload.blobCache;
                      var base64 = reader.result.split(',')[1];
                      var blobInfo = blobCache.create(id, file, base64);
                      blobCache.add(blobInfo);

                      /* call the callback and populate the Title field with the file name */
                      cb(blobInfo.blobUri(), { title: file.name });
                  };
                  reader.readAsDataURL(file);
              };

              input.click();
          }
      });
  </script>
</head>
<body>
<%= yield %>
<%=  debug(params) if Rails.env.development? %>
</body>
</html>